config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
  get "about" => "about#index"
  get "contact" => "contact#index"
  get "login" => "login#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/_about.html.erb
<div class="about-section">
  <h2>About Us</h2>
  <p>Welcome to our website! We are a company dedicated to providing top-notch products and services to our customers.</p>
  <p>Our team consists of highly skilled professionals who are passionate about what they do. We strive to exceed customer expectations and deliver exceptional results.</p>
  <p>Feel free to explore our website and learn more about our company and the services we offer. If you have any questions, don't hesitate to contact us.</p>
</div>

app/views/home/_home.html.erb
<h1>Welcome to the Home Page</h1>
<p>This is the home page of the application.</p>

app/views/home/index.html.erb
<%= stylesheet_link_tag("home") %>
<div id=home-content>
  <nav id="home-nav"> 
    <ul>
      <li><%= link_to("Home", root_path) %></li>
      <li><%= link_to("About", about_path) %></li>
      <li><%= link_to("Login", login_path) %></li>
    </ul>
  </nav>

  <main class="container">
    <%= turbo_frame_tag "index_main_content" do %>
      <%= render "home" %>
    <% end %>
  </main>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrmDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>